return {
  program = "inventory-coordinator",
  role = "coordinator",
  version = "0.1.0",
  runtime_entry = "src/main.lua",
  files = {
    { path = "README.md", source_path = "README.md" },
    { path = "src/main.lua", source_path = "src/main.lua" },
    { path = "src/app/release_service.lua", source_path = "src/app/release_service.lua" },
    { path = "src/app/runtime.lua", source_path = "src/app/runtime.lua" },
    { path = "src/deps/log.lua", source_path = "src/deps/log.lua" },
    { path = "src/infra/persistence.lua", source_path = "src/infra/persistence.lua" },
    { path = "src/model/config.lua", source_path = "src/model/config.lua" },
    { path = "src/model/cycle.lua", source_path = "src/model/cycle.lua" },
    { path = "src/model/plan.lua", source_path = "src/model/plan.lua" },
    { path = "src/model/schedule.lua", source_path = "src/model/schedule.lua" },
    { path = "src/model/transfer_queue.lua", source_path = "src/model/transfer_queue.lua" },
    { path = "src/model/warehouse_registry.lua", source_path = "src/model/warehouse_registry.lua" },
    { path = "src/ui/coordinator_view.lua", source_path = "src/ui/coordinator_view.lua" },
    { path = "src/ui/controller.lua", source_path = "src/ui/controller.lua" },
    { path = "src/ui/detail_view.lua", source_path = "src/ui/detail_view.lua" },
    { path = "src/ui/fmt.lua", source_path = "src/ui/fmt.lua" },
    { path = "src/ui/summary_model.lua", source_path = "src/ui/summary_model.lua" },
    { path = "src/ui/summary_view.lua", source_path = "src/ui/summary_view.lua" },
  },
  config_template = {
    path = "/etc/inventory-coordinator/config.lua",
    source_path = "install/templates/config.lua",
  },
}
